# -*- coding: utf-8 -*-
"""EX3-Markers_Plot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbVBC19smS2hG9CfVV8rMNuwPZnS7d3F
"""

pip install leafmap

import leafmap
import pandas as pd
import geopandas as gpd

import ee

map = leafmap.Map()
map

Earthquakes = "/content/Earthquakes_Data.csv"

df = pd.read_csv(Earthquakes)

print(df.columns)

print(df.head())

gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.Longitude, df.Latitude, crs="EPSG:4326"))

print(gdf.head())

map.add_points_from_xy(
    Earthquakes,
    x = "Longitude",
    y = "Latitude",
    size="marker_size",
    popup = ["Name","Depth","Magnitude","Year"],
    add_legend = True
)
map

gdf.to_file("Earthquake.geojson",driver="GeoJSON")

"""**World Continents Data Source = https://www.africageoportal.com/datasets/esri::world-continents/explore?location=-0.052342%2C0.000000%2C1.00**"""

Continents = "/content/World_Continents_-8423622284373332078.geojson"

gdf = gpd.read_file(Continents)

gdf.head()

map.add_geojson(Continents)
map

"""**Tectonic Plates Data Source = https://github.com/fraxen/tectonicplates/tree/master/GeoJSON**"""

Tectonic_Plates = "https://raw.githubusercontent.com/fraxen/tectonicplates/master/GeoJSON/PB2002_plates.json"

map.add_geojson(Tectonic_Plates)
map

Tectonic_gdf = gpd.read_file(Tectonic_Plates)
Tectonic_gdf.to_file("Tectonic_Plates.geojson", driver="GeoJSON")